POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "seppo",
    "name": "Jani Miettinen",
    "password": "salasana"
}











<!--content-type: application/json

{ 
    "username": "janimiet",
    "name": "Jani Miettinen",
    "password": "salainen"
}

